### ISSUE TITLE
Incorrect UDP section generation

### ISSUE THREAD

**Issue by fsanaulla** [APISENSE/embed-influxDB#13]
Instead of generating `[[udp]]` it generates `[udp]`. Solution can be find [here](https://github.com/mwanji/toml4j/issues/35). 
In short, we need wrap UDP section content in List, when putting it to config map.

**Comment by aveuiller** [comment]
So it's [an array](https://github.com/toml-lang/toml#array-of-tables), I didn't take that into account to be honest.

Since only some sections of the configuration will be arrays, we will have to create a new method `isArray` in the `ConfigurationSection` interface to help the `ConfigurationWriter` wrapping the needed sections.

Do you want to implement it, or shall I?

**Comment by fsanaulla** [comment]
Yeah, I will implement it.

**Comment by aveuiller** [comment]
Thanks for the contribution! :)
